# @schema
# description: ArgoCD parameters section
# type: object
# @schema
argocd:
  # @schema
  # description: Namespace where ArgoCD has been installed
  # type: string
  # default: krateo-system
  # @schema
  namespace: krateo-system
  # @schema
  # description: ArgoCD application configuration section
  # type: object
  # @schema
  application:
    # @schema
    # description: ArgoCD Application project
    # type: string
    # default: default
    # @schema
    project: default
    # @schema
    # description: ArgoCD Application source parameters section
    # type: object
    # @schema
    source:
      # @schema
      # type: string
      # description: ArgoCD Application source path inside the repository created by the template
      # default: chart/
      # @schema
      path: chart/
    # @schema
    # description: ArgoCD Application destination parameters section
    # type: object
    # @schema
    destination:
      # @schema
      # description: ArgoCD Application target cluster
      # type: string
      # format: idn-hostname
      # default: https://kubernetes.default.svc 
      # @schema
      server: https://kubernetes.default.svc
      # @schema
      # description: ArgoCD Application target namespace
      # type: string
      # default: fireworks-app
      # @schema
      namespace: fireworks-app
    # @schema
    # description: ArgoCD Application synchronization policies section
    # type: object
    # @schema
    syncPolicy:
      # @schema
      # description: ArgoCD Application automated synchronization policies section
      # type: object
      # @schema
      automated:
        # @schema
        # type: boolean
        # default: true
        # @schema
        prune: true
        # @schema
        # type: boolean
        # default: true
        # @schema
        selfHeal: true

# @schema
# description: Helm Chart parameters section
# type: object
# @schema
app:
  # @schema
  # description:  Helm Chart service parameters section
  # type: object
  # @schema
  service:
    # @schema
    # description: Helm Chart service type
    # type: string
    # enum:
    # - NodePort
    # - LoadBalancer
    # deault: NodePort
    # @schema
    type: NodePort
    # @schema
    # description: Helm Chart service port
    # type: integer
    # minimum: 30000
    # maximum: 32767
    # default: 31180
    # @schema
    port: 31180

# @schema
# description: Git Repository parameters section
# type: object
# @schema
git:
  # @schema
  # type: boolean
  # default: true
  # description: UnsupportedCapabilities enable Go-Git transport.UnsupportedCapabilities Azure DevOps requires capabilities multi_ack / multi_ack_detailed, which are not fully implemented in go-git library and by default are included in transport.UnsupportedCapabilities.
  # @schema
  unsupportedCapabilities: true
  # @schema
  # type: boolean
  # default: true
  # description: Insecure is useful with hand made SSL certs
  # @schema
  insecure: true
  # @schema
  # description: Parameters section for Git repository used as template for the application skeleton
  # type: object
  # @schema
  fromRepo:
    # @schema
    # description: Url of the source Git repository
    # type: string
    # format: idn-hostname
    # examples: [https://api.example.org]
    # default: https://github.com
    # @schema
    scmUrl: https://github.com
    # @schema
    # description: Organization/group/subgroup of the source Git repository
    # type: string
    # default: krateoplatformops-blueprints
    # @schema
    org: krateoplatformops-blueprints
    # @schema
    # description: Name for the source Git repository
    # type: string
    # default: github-scaffolding
    # @schema
    name: github-scaffolding
    # @schema
    # description: Branch of Git repository used as template for the application skeleton
    # type: string
    # default: main
    # @schema
    branch: main
    # @schema
    # description: Path of Git repository used as template for the application skeleton
    # type: string
    # default: skeleton/
    # @schema
    path: skeleton/
    # @schema
    # description: References to the secrets that contain the credentials required to clone the repository (in case of private ones)
    # type: object
    # @schema
    credentials:
      # @schema
      # description: AuthMethod defines the authentication mode.
      # type: string
      # enum:
      # - generic
      # - bearer
      # default: generic
      # @schema
      authMethod: generic
      # @schema
      # description: Reference details about the secret where the credentials are stored
      # type: object
      # @schema
      secretRef:
        # @schema
        # description: Namespace of the secret where the credentials are stored
        # type: string
        # default: krateo-system
        # @schema
        namespace: krateo-system
        # @schema
        # description: Name of the secret where the credentials are stored
        # type: string
        # default: github-repo-creds
        # @schema
        name: github-repo-creds
        # @schema
        # description: Key of the secret to use
        # type: string
        # default: token
        # @schema
        key: token
  # @schema
  # description: Parameters section for Git repository that will be created by Krateo
  # type: object
  # @schema
  toRepo:
    # @schema
    # description: Url of the target Git repository
    # type: string
    # format: idn-hostname
    # examples: [https://api.example.org]
    # default: https://github.com
    # @schema
    scmUrl: https://github.com
    # @schema
    # description: Organization/group/subgroup for the target Git repository
    # type: string
    # default: krateoplatformops-test
    # @schema
    org: krateoplatformops-test
    # @schema
    # description: Name for the target Git repository
    # type: string
    # required: true
    # @schema
    name: ""
    # @schema
    # description: Branch for the target Git repository
    # type: string
    # default: main
    # @schema
    branch: main
    # @schema
    # description: Path of the target Git repository 
    # type: string
    # default: /
    # @schema
    path: /
    # @schema
    # description: References to the secrets that contain the credentials required to commit to the target repository (in case of private ones)
    # type: object
    # @schema
    credentials:
      # @schema
      # description: AuthMethod defines the authentication mode.
      # enum:
      # - generic
      # - bearer
      # default: generic
      # @schema
      authMethod: generic
      # @schema
      # description: Reference details about the secret where the credentials are stored
      # type: object
      # @schema
      secretRef:
        # @schema
        # description: Namespace of the secret where the credentials are stored
        # type: string
        # default: krateo-system
        # @schema
        namespace: krateo-system
        # @schema
        # description: Name of the secret where the credentials are stored
        # type: string
        # default: github-repo-creds
        # @schema
        name: github-repo-creds
        # @schema
        # description: Key of the secret to use
        # type: string
        # default: token
        # @schema
        key: token
    # @schema
    # description: Whether the repository is private
    # type: boolean
    # default: false
    # @schema
    private: false
    # @schema
    # description: Whether the repository must be initialized
    # type: boolean
    # default: true
    # @schema
    initialize: true
    # @schema
    # description: DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted.
    # enum:
    # - Delete
    # - Orphan
    # default: Delete
    # @schema
    deletionPolicy: Delete
    # @schema
    # description: Whether to enable verbose logging for Repo controller 
    # type: boolean
    # default: false
    # @schema
    verbose: false