apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.argocd.namespace }}
  labels:
    {{- include "github-scaffolding.labels" . | nindent 4 }}
spec:
  project: {{ .Values.argocd.application.project | default "default" }}
  source:
    repoURL: {{ include "github-scaffolding.toRepoUrl" . }}
    targetRevision: {{ .Values.git.toRepo.branch }}
    path: {{ .Values.argocd.application.source.path }}
  destination:
    server: {{ .Values.argocd.application.destination.server }}
    namespace: {{ .Values.argocd.application.destination.namespace }}
  syncPolicy:
    {{- if and .Values.global (eq (toString .Values.global.gracefullyPaused) "true") }}
    automated: {}
    {{- else }}
    automated:
      prune: {{ .Values.argocd.application.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.argocd.application.syncPolicy.automated.selfHeal }}
    {{- end }}
    syncOptions:
      - CreateNamespace=true